<?php 

$t = "\t";
$n = "\n";
$xml = '<?xml version="1.0" encoding="UTF-8"?>'."$n";
$xml.= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."$n";

$xml2 = '<?xml version="1.0" encoding="UTF-8"?>'."$n";
$xml2.= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."$n";

$xml3 = '<?xml version="1.0" encoding="UTF-8"?>'."$n";
$xml3.= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."$n";

$xml4 = '<?xml version="1.0" encoding="UTF-8"?>'."$n";
$xml4.= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."$n";


$xml5 = '<?xml version="1.0" encoding="UTF-8"?>'."$n";
$xml5.= '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."$n";

$xml6 = '<?xml version="1.0" encoding="UTF-8"?>'."$n";
$xml6.= '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'."$n";

$html5 = '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>Site Map - Generated by hoingay.online</title>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<style type="text/css">
body {
background-color: #DDD;
font: normal 80%  "Trebuchet MS", "Helvetica", sans-serif;
margin:0;
text-align:center;
}
#cont{
margin:auto;
width:800px;
text-align:left;
}
a:link,a:visited {
color: #0180AF;
text-decoration: underline;
}
a:hover {
color: #666;
}
h1 {
background-color:#fff;
padding:20px;
color:#00AEEF;
text-align:left;
font-size:32px;
margin:0px;
}
h3 {
font-size:12px;
background-color:#B8DCE9;
margin:0px;
padding:10px;
}
h3 a {
float:right;
font-weight:normal;
display:block;
}
th {
text-align:center;
background-color:#00AEEF;
color:#fff;
padding:4px;
font-weight:normal;
font-size:12px;
}
td {
font-size:12px;
padding:3px;
text-align:left;
}
tr {background: #fff}
tr:nth-child(odd) {background: #f0f0f0}
#footer {
background-color:#B8DCE9;
padding:10px;
}
.pager,.pager a {
background-color:#00AEEF;
color:#fff;
padding:3px;
}
.lhead {
background-color:#fff;
padding:3px;
font-weight:bold;
font-size:16px;
}
.lpart {
background-color:#f0f0f0;
padding:0px;
}
.lpage {
font:normal 12px verdana;
}
.lcount {
background-color:#00AEEF;
color:#fff;
padding:2px;
margin:2px;
font:bold 12px verdana;
}
a.aemphasis {
color:#009;
font-weight:bold;
}
</style>

</head>
<body>
<div id="cont">
<h1>HTML Site Map</h1>
<h3><a href="http://hoingay.online">Homepage</a>
Last updated: Auto
</h3>


<table cellpadding="0" cellspacing="0" border="0" width="100%">

<tr valign="top">
<td class="lpart" colspan="100"><div class="lhead">/
<span class="lcount">All pages</span></div>

<table cellpadding="0" cellspacing="0" border="0" width="100%">
<tr><td class="lpage"><a href="http://hoingay.online/" title="Hỏi Ngay Online">Hỏi Ngay Online</a></td></tr>
<tr><td class="lpage"><a href="http://hoingay.online/dang-ky-tai-khoan" title="Đăng Ký - Hỏi Ngay Online">Đăng Ký - Hỏi Ngay Online</a></td></tr>
<tr><td class="lpage"><a href="http://hoingay.online/dang-nhap" title="Đăng Nhập - Hỏi Ngay Online">Đăng Nhập - Hỏi Ngay Online</a></td></tr>';
$date = $response['date'];
$date = strtotime($date);
$date = date(DATE_W3C, $date);
$lastmod = date('Y-m-d\TH:i:sP');
?>

<?php


	
include("ketnoi.php");


$kq=mysql_query("SELECT id from data ORDER BY id DESC LIMIT 1") or die ("Không thể xuất thông tin Bảng tb ".mysql_error());
while ($row=mysql_fetch_array($kq)) 
{ 

$id2 = mysql_real_escape_string($row['id']);

 $chiaxml = ceil($id2/4);
$xml11 = $chiaxml-1;
$xml22 = $chiaxml*2-2;
$xml33 = $chiaxml*3-3;
$xml44 = $chiaxml*4-4;
echo $chiaxml;


}
/////////sdsad
$xml5.= '<sitemap>'."$n";
	$xml5.= "$t".'<loc>'."http://hoingay.online/xml/sitemap.xml.gz".'</loc>'."$n";
	$xml5.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml5.= '</sitemap>'."$n";

$xml5.= '<sitemap>'."$n";
	$xml5.= "$t".'<loc>'."http://hoingay.online/xml/sitemap2.xml.gz".'</loc>'."$n";
	$xml5.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml5.= '</sitemap>'."$n";

$xml5.= '<sitemap>'."$n";
	$xml5.= "$t".'<loc>'."http://hoingay.online/xml/sitemap3.xml.gz".'</loc>'."$n";
	$xml5.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml5.= '</sitemap>'."$n";



$xml5.= '<sitemap>'."$n";
	$xml5.= "$t".'<loc>'."http://hoingay.online/xml/sitemap4.xml.gz".'</loc>'."$n";
	$xml5.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml5.= '</sitemap>'."$n";

$xml5.= '<sitemap>'."$n";
	$xml5.= "$t".'<loc>'."http://hoingay.online/xml/sitemap5.xml.gz".'</loc>'."$n";
	$xml5.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml5.= '</sitemap>'."$n";

$xml5.= '</sitemapindex>';
$handle = fopen('sitemap.xml','w+');
fwrite($handle,$xml5);
fclose($handle);
//////////
$kq=mysql_query("SELECT id from data ORDER BY id DESC LIMIT $xml11") or die ("Không thể xuất thông tin Bảng tb ".mysql_error());
while ($row=mysql_fetch_array($kq)) 
{ 

$id2 = mysql_real_escape_string($row['id']);

 $sql = "select * from data where id = $id2";
  $result = mysql_query($sql);
  $data = mysql_fetch_array ($result);
$xml.= '<url>'."$n";
//
$cauhoi = convert_vi_to_en($data['cauhoi']);
 $gcauhoi =  preg_replace('([^a-zA-Z0-9])', '-', $cauhoi);  
	
//

	$xml.= "$t".'<loc>'."http://hoingay.online/".$gcauhoi."/".$data['id'].'.html</loc>'."$n";
	//$xml.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml.= '</url>'."$n";


}
$xml.= '</urlset>';
$handle = fopen('xml/sitemap.xml.gz','w+');
fwrite($handle,$xml);
fclose($handle);
//////////
$kq=mysql_query("SELECT id from data ORDER BY id DESC LIMIT $xml11,$xml22") or die ("Không thể xuất thông tin Bảng tb ".mysql_error());
while ($row=mysql_fetch_array($kq)) 
{ 

$id2 = mysql_real_escape_string($row['id']);

 $sql = "select * from data where id = $id2";
  $result = mysql_query($sql);
  $data = mysql_fetch_array ($result);
$xml2.= '<url>'."$n";
//

$cauhoi = convert_vi_to_en($data['cauhoi']);
 $gcauhoi =  preg_replace('([^a-zA-Z0-9])', '-', $cauhoi);  
	$xml2.= "$t".'<loc>'."http://hoingay.online/".$gcauhoi."/".$data['id'].'.html</loc>'."$n";
//
	//$xml2.= "$t".'<loc>'."http://hoingay.online/view?id=".$data['id'].'</loc>'."$n";
	//$xml2.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml2.= '</url>'."$n";


}
$xml2.= '</urlset>';
$handle = fopen('xml/sitemap2.xml.gz','w+');
fwrite($handle,$xml2);
fclose($handle);
///////////
$kq=mysql_query("SELECT id from data ORDER BY id DESC LIMIT $xml22,$xml33") or die ("Không thể xuất thông tin Bảng tb ".mysql_error());
while ($row=mysql_fetch_array($kq)) 
{ 

$id2 = mysql_real_escape_string($row['id']);

 $sql = "select * from data where id = $id2";
  $result = mysql_query($sql);
  $data = mysql_fetch_array ($result);
$xml3.= '<url>'."$n";
//
$cauhoi = convert_vi_to_en($data['cauhoi']);
 $gcauhoi =  preg_replace('([^a-zA-Z0-9])', '-', $cauhoi);  
	$xml3.= "$t".'<loc>'."http://hoingay.online/".$gcauhoi."/".$data['id'].'.html</loc>'."$n";
//
	//$xml3.= "$t".'<loc>'."https://hoingay.online/view?id=".$data['id'].'</loc>'."$n";
	//$xml3.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml3.= '</url>'."$n";


}
$xml3.= '</urlset>';
$handle = fopen('xml/sitemap3.xml.gz','w+');
fwrite($handle,$xml3);
fclose($handle);
////////////////////////////////////////
$kq=mysql_query("SELECT id from data ORDER BY id DESC LIMIT $xml33,$xml44") or die ("Không thể xuất thông tin Bảng tb ".mysql_error());
while ($row=mysql_fetch_array($kq)) 
{ 

$id2 = mysql_real_escape_string($row['id']);

 $sql = "select * from data where id = $id2";
  $result = mysql_query($sql);
  $data = mysql_fetch_array ($result);
$xml4.= '<url>'."$n";
$cauhoi = convert_vi_to_en($data['cauhoi']);
 $gcauhoi =  preg_replace('([^a-zA-Z0-9])', '-', $cauhoi);  
	$xml4.= "$t".'<loc>'."http://hoingay.online/".$gcauhoi."/".$data['id'].'.html</loc>'."$n";
	//$xml4.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml4.= '</url>'."$n";


}
$xml4.= '</urlset>';
$handle = fopen('xml/sitemap4.xml.gz','w+');
fwrite($handle,$xml4);
fclose($handle);











////////////////////////////////////////tai khoan
$kq=mysql_query("SELECT id from member ORDER BY id DESC") or die ("Không thể xuất thông tin Bảng tb ".mysql_error());
while ($row=mysql_fetch_array($kq)) 
{ 

$id2 = mysql_real_escape_string($row['id']);

 $sql = "select * from member where id = $id2";
  $result = mysql_query($sql);
  $data = mysql_fetch_array ($result);
$xml6.= '<url>'."$n";
	$xml6.= "$t".'<loc>'."http://hoingay.online/user?id=".$data['id']."&u=".$data['username'].'</loc>'."$n";
	//$xml4.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";
	$xml6.= '</url>'."$n";


}
$xml6.= '</urlset>';
$handle = fopen('xml/sitemap5.xml.gz','w+');
fwrite($handle,$xml6);
fclose($handle);
















//trang so do
//$kq=mysql_query("SELECT id from data ORDER BY id DESC") or die ("Không thể xuất thông tin Bảng tb ".mysql_error());
//while ($row=mysql_fetch_array($kq)) 
//{ 

//$id2 = mysql_real_escape_string($row['id']);

 //$sql = "select * from data where id = $id2";
  //$result = mysql_query($sql);
  //$data = mysql_fetch_array ($result);
  //
  //$cauhoi = convert_vi_to_en($data['cauhoi']);
 //$gcauhoi =  preg_replace('([^a-zA-Z0-9])', '-', $cauhoi);  
	//$xml4.= "$t".'<loc>'."http://hoingay.online/".$gcauhoi."/".$data['id'].'.html</loc>'."$n";
  //
	//$html5.= '<tr><td class="lpage"><a href="'."http://hoingay.online/".$gcauhoi."/".$data['id'].'" title="'.$data['cauhoi'].'">'.$data['cauhoi'].'</a></td></tr>';
	//$html5.= "$t".'<lastmod>'.$lastmod.'</lastmod>'."$n";


//}
//$html5.= '</table>
//</td>
//</tr>

//</table><div id="footer">
//Page generated by Hoingay.online - <a target="_blank" href="http://'.$_SERVER["HTTP_HOST"]'">Google XML sitemap and html sitemaps generator</a>
//|
//Copyright &copy; 2005-2016';
//
//$html5.='</div>
//</div>
//</body>
//</html>';
//$handle = fopen('sitemap.html','w+');
//fwrite($handle,$html5);
//fclose($handle);
?>
<?php
function convert_vi_to_en($str) {
        $str = preg_replace("/(à|á|ạ|ả|ã|â|ầ|ấ|ậ|ẩ|ẫ|ă|ằ|ắ|ặ|ẳ|ẵ)/", 'a', $str);
        $str = preg_replace("/(è|é|ẹ|ẻ|ẽ|ê|ề|ế|ệ|ể|ễ)/", 'e', $str);
        $str = preg_replace("/(ì|í|ị|ỉ|ĩ)/", 'i', $str);
        $str = preg_replace("/(ò|ó|ọ|ỏ|õ|ô|ồ|ố|ộ|ổ|ỗ|ơ|ờ|ớ|ợ|ở|ỡ)/", 'o', $str);
        $str = preg_replace("/(ù|ú|ụ|ủ|ũ|ư|ừ|ứ|ự|ử|ữ)/", 'u', $str);
        $str = preg_replace("/(ỳ|ý|ỵ|ỷ|ỹ)/", 'y', $str);
        $str = preg_replace("/(đ)/", 'd', $str);
        $str = preg_replace("/(À|Á|Ạ|Ả|Ã|Â|Ầ|Ấ|Ậ|Ẩ|Ẫ|Ă|Ằ|Ắ|Ặ|Ẳ|Ẵ)/", 'A', $str);
        $str = preg_replace("/(È|É|Ẹ|Ẻ|Ẽ|Ê|Ề|Ế|Ệ|Ể|Ễ)/", 'E', $str);
        $str = preg_replace("/(Ì|Í|Ị|Ỉ|Ĩ)/", 'I', $str);
        $str = preg_replace("/(Ò|Ó|Ọ|Ỏ|Õ|Ô|Ồ|Ố|Ộ|Ổ|Ỗ|Ơ|Ờ|Ớ|Ợ|Ở|Ỡ)/", 'O', $str);
        $str = preg_replace("/(Ù|Ú|Ụ|Ủ|Ũ|Ư|Ừ|Ứ|Ự|Ử|Ữ)/", 'U', $str);
        $str = preg_replace("/(Ỳ|Ý|Ỵ|Ỷ|Ỹ)/", 'Y', $str);
        $str = preg_replace("/(Đ)/", 'D', $str);
        return $str;
    }
?>
 